server {
    listen 443 ssl http2;
    server_name mitra.megahkreasindo.my.id;

    ssl_certificate /etc/letsencrypt/live/megahkreasindo.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/megahkreasindo.my.id/privkey.pem;

    include /home/parkdims-mki/apps/nginx/snippets/ssl-params.conf;
    include /home/parkdims-mki/apps/nginx/snippets/security-headers.conf;

    location /e-sop-atrbpn/api/ {
        rewrite ^/e-sop-atrbpn/api/(.*)$ /api/$1 break;
        proxy_pass http://localhost:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 20M;
    }

    location /e-sop-atrbpn/ {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}